# Default values for Devtron-Cronjobs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

jobs:
  # first cron
  - name: hello-world
    image:
      repository: hello-world
      tag: latest
      imagePullPolicy: IfNotPresent
    schedule: "* * * * *"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Allow
    restartPolicy: OnFailure
    
    # optional env vars 
    env:
    - name: ECHO_VAR
      value: "busybox"
    # envFrom:
    # - secretRef:
    #     name: SECRET_DATA
    # - configMapRef:
    #     name: CONFIG_DATA
    schedule: "* * * * *"
    command: ["/bin/sh"]
    args:
      - "-c"
      - "echo $(date) - hello from $ECHO_VAR"
      - "echo $(date) - loaded secret $SECRET_DATA"
      - "echo $(date) - loaded config $CONFIG_DATA"
    serviceAccount:
      name: "busybox-serviceaccount"
    resources:
      limits:
        cpu: 50m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 256Mi
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: Never
    nodeSelector:
      type: infra
    tolerations:
    - effect: NoSchedule
      operator: Exists
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/e2e-az-name
              operator: In
              values:
              - e2e-az1
              - e2e-az2