apiVersion: installer.devtron.ai/v1alpha1
kind: Installer
metadata:
  name: installer-devtron
  namespace: devtroncd
spec:
  url: https://raw.githubusercontent.com/devtron-labs/devtron/v0.6.0/manifests/installation-script
