apiVersion: installer.devtron.ai/v1alpha1
kind: Installer
metadata:
  name: installer-devtron
  namespace: default
spec:
  url: https://raw.githubusercontent.com/devtron-labs/devtron/v0.2.6/manifests/installation-script
