{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  {{- if .Values.service.name  }}
  name: {{ .Values.service.name}}
  {{- else }}
  name: {{ template ".servicename" . }}
  {{- end }}
  labels:
    app: {{ template ".Chart.Name .name" $ }}
    chart: {{ template ".Chart.Name .chart" $ }}
    release: {{ $.Release.Name }}
    releaseVersion: {{ $.Values.releaseVersion | quote }}
    pipelineName: {{ .Values.pipelineName }}
{{- if .Values.appLabels }}
{{ toYaml .Values.appLabels | indent 4 }}
{{- end }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
{{- if (and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerSourceRanges )}}
  loadBalancerSourceRanges: 
 {{- range .Values.service.loadBalancerSourceRanges }}
  - {{ . }}
 {{- end }}
{{- end }}
  ports:
    {{- range .Values.ContainerPort }}
      {{- if .servicePort }}
    - port: {{ .servicePort }}
      {{- else }}
    - port: {{ .port }}
       {{- end }}
      {{- if .targetPort }}
      targetPort: {{ .targetPort }}
      {{- else }}
      targetPort: {{ .name }}
      {{- end }}
      {{- if (and (eq $.Values.service.type "NodePort") .nodePort )}}
      nodePort: {{ .nodePort }}
      {{- end }}
      protocol: TCP
      name: {{ .name }}
    {{- end }}
      {{- if $.Values.appMetrics }}
    - port: 9901
      name: envoy-admin
      {{- end }}
  selector:
    app: {{ template ".Chart.Name .name" . }}
{{- end }}
---
{{- if .Values.service-headless.enabled }}

apiVersion: v1
kind: Service
metadata:
  {{- if .Values.statefulSetConfig.serviceName  }}
  name: {{ .Values.statefulSetConfig.serviceName }}
  {{- else }}
  name: {{ template ".servicename" . }}-headless
  {{- end }}
  labels:
    app: {{ template ".Chart.Name .name" $ }}
    chart: {{ template ".Chart.Name .chart" $ }}
    release: {{ $.Release.Name }}
    releaseVersion: {{ $.Values.releaseVersion | quote }}
    pipelineName: {{ .Values.pipelineName }}
{{- if .Values.appLabels }}
{{ toYaml .Values.appLabels | indent 4 }}
{{- end }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  clusterIP: None
  ports:
    {{- range .Values.ContainerPort }}
      {{- if .servicePort }}
    - port: {{ .servicePort }}
      {{- else }}
    - port: {{ .port }}
       {{- end }}
      {{- if .targetPort }}
      targetPort: {{ .targetPort }}
      {{- else }}
      targetPort: {{ .name }}
      {{- end }}
      {{- if (and (eq $.Values.service.type "NodePort") .nodePort )}}
      nodePort: {{ .nodePort }}
      {{- end }}
      protocol: TCP
      name: {{ .name }}
    {{- end }}
      {{- if $.Values.appMetrics }}
    - port: 9901
      name: envoy-admin
      {{- end }}
  selector:
    app: {{ template ".Chart.Name .name" . }}
  type: ClusterIP
{{- if (and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerSourceRanges )}}
  loadBalancerSourceRanges: 
 {{- range .Values.service.loadBalancerSourceRanges }}
      - {{ . }}
 {{- end }}
{{- end }}
{{- end}}